name: Check Backend
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go: ['1.16']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: cd backend && go test -v ./...
      - run: cd backend && go build
